### ISSUE TITLE
incorporate more benefits text

### ISSUE THREAD

**Issue by mcmanus** [dohwg/draft-ietf-doh-dns-over-https#100]
on list jon mattsson points out that we don't mention some pretty key architectural benefits of doh such as authentication, amplification resistance, etc. on list as "changes for draft-ietf-doh-dns-over-https-03". #99 is meant to address this

**Comment by mcmanus** [comment]
@fantuz I agree with almost everything you say, but I don't think the DoH protocol doc is the place to got at all of these things at this length. I'm just trying to give a flavor of the implications of using the http ecosystem - which you go into in much deeper detail. The document has to focus on how you do that.

my suggestion would be you raise the concept of a separate applicability/use-case document if you think this is valuable.. you could raise this as part of the charter discussion for DoH.

Or you could just work on a really great blog post :)

**Comment by fantuz** [comment]
Thank you @mcmanus I will follow all of your suggestions, just a matter of having some time to say something "useful" and hopefully, possibly correct. I am still willing to follow all of the discussions around the doh topic, I have a lot to learn from all of you, really proud of your consideration.

I understand the logic of defining precise specifications and how-to-implement, proper of drafting RFC. I fully support the criteria of "referring to" other standing and specific RFCs by keeping the transversal implications outside of the doc, as it might over-confuse implementors and this is not the goal.

Sorry for that, I just wanted to mention some of the possible "arguments" or side-effects (my first time in participating in such exciting discussions and group). My congratulations to all of the working group and supporters, for all the efforts being put into this important draft 🥇
