### ISSUE TITLE
Don't require HTTP/2

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#11]
I think that it is fine - or more precisely, invaluable - to explain what the semantics of server push are.  But you don't actually require HTTP/2 for this protocol to work.

The only thing that requiring HTTP/2 gets you is tighter constraints on TLS usage.  You can get those same constraints with some deployment recommendations.

I would support strong recommendations that said HTTP/2 is useful for its multiplexing as well as similarly strong advice about following the advice in RFC 7525.  Those are both good practice.

**Comment by mcmanus** [comment]
fairly clear feedback from singapore to change this to an endorsement (SHOULD) with better explanatory text focusing on performance and scale.

**Comment by chantra** [comment]
What are the drawbacks of HTTP/2? Less readily available libraries? more complex protocol?
 Potential difficulties in integrating with current fronting stacks that may not be HTTP/2 ready?

On one hand, I feel like it may be easier to just enforce 1 stack for now rather than having to support multiple flavor of client/server protocols. A suboptimal HTTP/2 implementation may just be similar to HTTP/1 but at least we can try to move forward toward multiplexing. Making HTTP/2 a should may just leave us in limbo in HTTP/1 land.

**Comment by mcmanus** [comment]
@chantra the singapore meeting is available here https://www.youtube.com/watch?v=1_s1ND_D92I&feature=youtu.be .. goto the 12 minute mark to review the discussion (wrt your question about drawbacks).

**Comment by paulehoffman** [comment]
Text is in https://github.com/dohwg/draft-ietf-doh-dns-over-https/pull/34

**Comment by paulehoffman** [comment]
Last PR accepted. I suspect there will be a bit more wordsmithing, but this should cover the main issue well.

**Comment by chantra** [comment]
> @chantra the singapore meeting is available here https://www.youtube.com/watch?v=1_s1ND_D92I&feature=youtu.be .. goto the 12 minute mark to review the discussion (wrt your question about drawbacks).

thanks, I was in the room, but my notes were sparse and some of the cons I remembered of were more inconvenience to me than blockers.

What I am not getting from the current spec, and which I believe @paulehoffman touched on in https://github.com/dohwg/draft-ietf-doh-dns-over-https/pull/34#discussion_r153363292, is that it is unclear whether or not a minimum HTTP version must be supported. Based on https://tools.ietf.org/html/rfc7230#appendix-A , do we consider that by supporting HTTP/1.1 we get HTTP/1.0 for free and consider 0.9 not an option?
Wouldn't not mandating a required version prevent client/server from having a known version to use?
Can we make this clearer maybe?

**Comment by mcmanus** [comment]
The decision was to rely only on HTTP semantics and not versions. So any HTTP implementation that is acceptable to its peer can be used.
