### ISSUE TITLE
[RFC6961] is deprecated in TLS 1.3

### ISSUE THREAD

**Issue by emanjon** [dohwg/draft-ietf-doh-dns-over-https#115]
"DNS API servers SHOULD utilize OCSP Stapling [RFC6961] to provide the client with certificate revocation information that does not require contacting a third party."

TLS 1.3 will probably be published before DOH and TLS 1.3 deprecates/obsoletes RFC 6961. TLS 1.3 uses only RFC 6066. Maybe you should refer to both RFC 6066 and RFC 6961.

**Comment by paulehoffman** [comment]
Good catch! Open as PR #119.

**Comment by mcmanus** [comment]
closed by #119
