### ISSUE TITLE
Trust and use of DNS API servers

### ISSUE THREAD

**Issue by emanjon** [dohwg/draft-ietf-doh-dns-over-https#117]
"A client MUST NOT trust a DNS API server simply because it was discovered, or because the client was told to trust the DNS API server by an untrusted party. Instead, a client MUST only trust DNS API server that is configured as trustworthy."

This is all true, but I think the draft should elaborate on use. My assumption is that a DNS API client may use an untrusted DNS server discovered with e.g. DHCP. This is clearly better than DNS over UDP/TCP, but clearly worse than use of a trusted DNS API server. I think the draft should elaborate whether a DNS API client may use an untrusted DOH API server or not.

I think the draft should state that an DNS API client MAY use an untrusted DNS API server or that an DNS API client SHALL NOT use an untrusted DNS API server.

**Comment by mcmanus** [comment]
Thanks for the comments. I think the draft takes the right tact with trust - but trust is a client concept.

A client policy might certainly choose to trust a DHCP (or pvd) configuration. Server identity in such cases might use address based certs or a configuration like pvd might be able to provide an address/uri pair.

**Comment by paulehoffman** [comment]
I agree with Patrick here, and don't think the changed wording will help with interoperability or security.

**Comment by mcmanus** [comment]
there is also the obliquely related (but not exactly the same) issues around out-of-band or opportunistic dns that were discussed at the end of the working group meeting in london. Those are clearly out of scope for this doc, we have consensus they are out of scope for this doc, and this language is meant to clarify that.

So I'll close the issue - but if the group has strong feelings that this language doesn't meet that goal then we should still adjust the text.
