### ISSUE TITLE
More details on retry vs. fallback mechanisms, HTTP error handling, some minor wording

### ISSUE THREAD

**Issue by fantuz** [dohwg/draft-ietf-doh-dns-over-https#124]
Hello, some comments on the "security considerations" section.

> A client can use DNS over HTTPS as one of multiple mechanisms to obtain DNS data. If a client of this protocol encounters an HTTP error after sending a DNS query, and then falls back to a different DNS retrieval mechanism, doing so can weaken the privacy expected by the user of the client.

Why refering explicitely to "DNS over HTTPS" ? From a draft point of view, that was a previous implementation hence "only for historical reference" ? Either mention many or none. Or use the correct name from --- abstract "This document describes how to run DNS service over HTTP using https:// URIs."

Text shall be, in my opinion:
`A client WILL HAVE TO use [..] multiple mechanisms to obtain DNS data, not subject of the draft. A client will express a choice on using DOH in DOH-enabled application, os set a classic nameserver os-wide. When using DOH to discover such DNS data, and when a client of this protocol encounters an HTTP error after sending a DNS query, such client COULD DECIDE to fall back to a different/alternative DNS retrieval mechanism. Beware ! Doing so can weaken the privacy expected by the user of the DOH client. Fallback mechanisms are not yet defined or publicised.`

And more, failing one HTTP request(s) is not always sympthom of DNS irreachability as a whole: Linux is configured to retry 3 times before giving up, asyncronously or not.... so the two following statements pose a little conflict to me:

> HTTP {{RFC7230}} is a stateless application level protocol and therefore DOH implementations do not provide stateful ordering guarantees between different requests.

and

> If a client of this protocol encounters an HTTP error after sending a DNS query, and then falls back to a different DNS retrieval mechanism, doing so can weaken the privacy expected by the user of the client.

As if on one hand we would like to admit that "retrying is normal" (default in Linux) (PLUS HERE WE ALLOW RETRYING in privacy degradation-mode as bonus) while OTOH we state that ordering or "relationship" between request is never to be guaranteed.... pure HTTP, no surprise.

But:
1. the client fallback is not that important here, and is pretty obvious how-to-fallback outside of DOH's vast panorama of choices.
2. we need to weaken the tightness of HTTP dialog, in a DNS way. A bad resolution is forever, TTL and caches docet.... A revalidation in case of first-time-error is possible AND wanted.

> DOH cannot be used as a transport for other protocols that require strict ordering.

That MUST be totally true, or totally false.
Some concept of "retry mechanism" shall be mentioned IMHO, not just in terms of providing meaningful HTTP errors (more will be a plus). Thinking from a DNS-client/server perspective we MIGHT WANT TO DELEGATE the explanation of "retry mechaninsm" and "fallback mechanisms" to external RFCs (allowing that a client-to-server or server-to-client messaging or connection CAN go bad for a second, that noone says how slow is a long timeout, how lingering influences etc) ... or include explanation of these, in a more generic way.

At the end, having more of HTTP errors filed (as protocol not allowed 405 for example, or 503/retry-after) will lead to make the client program become more "precise", enabling a 'full DOH way of retry" before failing hard or falling back (i.e resource busy vs servfail vs drop vs real slugginess of network vs bad luck etc etc).

The assumption DNS will work better or worse on HTTP, is just biased and over-rated. Obviously, it will work most of times AS-IS and as it used to work since ever, BUT DNS will have to deal with a non trivial layer of added HTTP servers. Assuming it will work better than before, is also too optimistic, as HTTP doesn't "solve" DNS at all. Hence, falling back has to be smart.

Last one: we also do not differentiate between DNS servfail and HTTP 500 servfail, neither we do provide a udpwireformat example of such way of "failing" (i.e. error document page containing SERVFAIL or NXDOMAIN templates, silly idea no?). For a client, a DNS failure is often hard failure, needs to be very visible.

Some time ago, on the list we took in account the possibility to describe two master DNS servers in APIs, but that was rejected for the time being ... I have another idea, using a specific header as Alt-Svc, might (slightly) mitigate fails or lagging if server still able to serve page but has "no good answer", or too many clients .... Alt-svc are not just intended for totally DIFFERENT services :)

This would be a DOH-on-DOH fallback similar to /etc/resolv.conf classic behaviour.

Have a nice evening,
max

**Comment by emanjon** [comment]
> A client WILL HAVE TO use [..] multiple mechanisms to obtain DNS data, not subject of the draft.

I don't think that is true. I think there are many scenarios where a hard fail is the correct alternative for security reasons. A web service using it's own DNS API Server should probably fail. And if I have configured my operating system to use https://example.com/doh because I care about privacy, I would certainly like it fail instead of trying something with less privacy.

**Comment by emanjon** [comment]
My example avobe is wrong, should be "use https://6.6.6.6/doh or something similar.

**Comment by fantuz** [comment]
yes i meant to allow the "fail-hard after retrying" but stay on DOH, do not leave it without notice.

And yes I support IP-only expression of doh-resolvers from the inception; that avoids chicken-egg problem, pure /etc/resolv.conf... :+1:

**Comment by mcmanus** [comment]
The comment in the security considerations section is just meant to reinforce "If you build your system around the properties of DoH and then fallback to non-Doh, your properties will be different." Pretty simple scope I'm not hearing wider consensus to change.

I'm going to recommend closing with no action.
