### ISSUE TITLE
HTTP server push

### ISSUE THREAD

**Issue by emanjon** [dohwg/draft-ietf-doh-dns-over-https#126]
>For HTTP server push ({{RFC7540}} Section 8.2) extra care must be taken to ensure that the pushed URI is one that the client would have directed the same query to if the client had initiated the request.

This does not seem like the right thing to base the decision on. Isn’t the important thing here that the DNS API server that did the server push is trustworthy for the DOH query (as stated earlier in the paragraph). A DNS API client can e.g. trust a set of DNS API servers, but always make queries to the one with lowest latency.

Unclear which “URI” the sentence talks about, there might be URIs on both the HTTP and DNS layers. I.e. the HTTP URI can push a DNS response with a URI RR.

**Comment by mcmanus** [comment]
the text says "is one" not "is the one" - it is trying to implicate there is a set of eligible uris. The reference is to the pushed URI - which is the HTTP URI. (a DNS RR would not be the pushed URI, it would be the pushed message body).

**Comment by mcmanus** [comment]
I think this is right, so lacking wider consensus to make a change I'll close it for now with no action..
