### ISSUE TITLE
Only SHOULD on matching HTTP expiration to TTL

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#13]
The draft says "the HTTP cache headers SHOULD be set to expire at the same time as the shortest DNS TTL in the response", which might not be strong enough.  A SHOULD might be OK for shorter, but allowing the value to increase might be unwise, depending on the caching model.

**Comment by mcmanus** [comment]
agree

**Comment by roryhewitt** [comment]
Seems like it should be MUST:

>  "the HTTP cache headers MUST be set to expire at the same time as (or sooner than) the shortest DNS TTL in the response"

**Comment by mcmanus** [comment]
closed by #21
