### ISSUE TITLE
Define the caching model

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#14]
The draft doesn't really tackle the question of caching fully right now.  I think that there is an implied hierarchy of caches that are in use.

The query first hits the DNS stack, which maintains its own cache.  Using the DNS TTL, that cache might decide to answer the query.

Then there is an HTTP stack, which might maintain its own cache.  Notably, none of the HTTP cache-busting techniques work from the perspective of the DNS client, so we have to be careful to observe that.  This particularly ordering makes #13 much worse.

Finally, a DNS API server might maintain its own cache.

**Comment by mcmanus** [comment]
worth noting that the DNS client doesn't have e2e cache busters with an http cache in the chain.. 

but does a traditional dns client have a cache buster? I've only really seen them explicitly ask another resolver.. which still seems possible here.

**Comment by PiotrSikora** [comment]
Could we add a sentence saying that the gateway decapsulating DNS-over-HTTPS MUST subtract the age of the HTTP response from the TTL inside the UDP packet before forwarding or consuming it (assuming that wouldn't break DNSSEC)? I think it would help with some of the confusion about interaction between HTTP and DNS caches.

**Comment by mcmanus** [comment]
probably worth noting HTTP "Age" to help the reader, but we want to be careful not to look like we're making changes to http when we aren't.

I think my read of the room in Singapore was that we don't want to encourage rewriting the DNS records. (DNSSEC being at least one reason).

**Comment by bemasc** [comment]
I think we _do_ want a DOH client to rewrite TTL when it is posing as a resolver to TTL-sensitive DNS clients.  TTL is excluded from DNSSEC signing, so there shouldn't be a problem with that.

**Comment by chantra** [comment]
on caching.... we should also clarify behaviours of caching proxies. If a caching proxy starts caching based on GET parameters, we can hit an issue when the DOH backends are providing geo-targeted based on querier IP. The first query would warm the cache and the second query from a second totally unrelated subnet would get a cached answer which is not the one it would get if it were to query the DOH server directly.
It may be worth having a section about potential caching caveats.

see https://mailarchive.ietf.org/arch/msg/doh/DAeqQpiy5vUY_4VKms4GLIAtpuw

**Comment by mcmanus** [comment]
@chantra what are you thinking of saying that is not covered by the http rfc's? (723x).

**Comment by chantra** [comment]
The current document talks about how using an ID of 0 is cache friendly. Which would lead to believe that if you have a layer of caching proxies in front of the DOH servers, they could cache the content and distribute it without re-querying the DOH backend for TTL time.
While this will work just fine in most cases, there is a caveat when the DOH servers return queries that are different/customized for different subnets such as with a DNS global load balancer.
I am not sure if this is covered in some aspect in one of the 723X RFCs, but I think we should drop a “consideration” for people to realize when to disable caching from reverse proxies. If there is already an RFC detailing this, great let’s link to it. If not I don’t think it deserves a lot, but we should let people be aware of the potential issue.

**Comment by mcmanus** [comment]
this issue is kind of broad.. I suggest we call #56 the base fix here, and we'll open follow on issues as necessary.
