### ISSUE TITLE
Do we still need Section 3?

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#148]
As input to the process, this was extremely valuable, but now that this is in WGLC, we're done with it.  Does the audience of the ultimate RFC need this information?  The only thing that I can see that is worth salvaging is a statement to the effect that DNS64 isn't explicitly supported.

**Comment by paulehoffman** [comment]
Yes, we still need it. We have not gone to IETF Last Call and, despite what some people think, the IETF gets to change a protocol significantly during IETF Last Call. But even after that, once it is an RFC, others will want to update the RFC. It is important to keep the requirements for them as well.

**Comment by paulehoffman** [comment]
Actually, we probably don't need it in the RFC as long as the one future requirement (for formats) is still there. Please see PR #169

**Comment by mcmanus** [comment]
closed by #169
