### ISSUE TITLE
Truncated responses

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#161]
I think that we should specify behaviour for truncated responses with the TC bit more clearly.  Right now the text is a little vague.  There seem to be three options:

1. mandate the generation of an HTTP error
2. mandate the forwarding of the truncated response
3. explicitly allow either
4. forbid the use of truncated responses and recommend fallback to TCP if the DNS API server is just making DNS requests to another server

I think that the draft current vacilates in the direction of 3, but I tend to like 1 or 4.  Choosing 4 wouldn't be consistent with the dnsop DNS-over-HTTP draft using DOH though.

**Comment by paulehoffman** [comment]
#3 is the right answer, so the text should just be stronger about it. If DOH requires #1 or #4, that means that the DNS server code will need to be heavily reworked to capture these from going out, which seems pointless. DOH clients can act like normal stubs: either they do or don't know about truncation and TC.

**Comment by mcmanus** [comment]
I agree - I don't think doh needs to behave differently here than any other datagram based client - i.e. its not a transport error. @paulehoffman can you do a pr to clarify?

**Comment by paulehoffman** [comment]
Will do.

**Comment by mcmanus** [comment]
closed by #170
