### ISSUE TITLE
Normalize the case of hostnames in DNS queries

### ISSUE THREAD

**Issue by mcmanus** [dohwg/draft-ietf-doh-dns-over-https#167]
offlist it was suggested to normalize hostname case for the benefit of caches.

its a good catch

we could go full on and just do it everywhere (as we do for message id) or we could just SHOULD it when the DNS message body appears in the uri-template.

**Comment by paulehoffman** [comment]
That would be reasonable if all queries were for hostnames, but they are not. Domain names can have any octet in any label. Although downcasing could help caches some, it can cause some queries where a label is really meant to be certain octets to fail.

**Comment by mcmanus** [comment]
too many dragons.
