### ISSUE TITLE
More clarification on example

### ISSUE THREAD

**Issue by roryhewitt** [dohwg/draft-ietf-doh-dns-over-https#18]
Maybe just me, but I would prefer more clarification on the request format:

> <33 bytes represented by the following hex encoding>
   abcd 0100 0001 0000 0000 0000 0377 7777
   0765 7861 6d70 6c65 0363 6f6d 0000 0100
   01

Is this directly from RFC1035? If so, perhaps a (very brief) explanation of the encoding, referencing the relevant standard would be useful. Also, perhaps an additional example showing EDNS(0) extensions being passed?

**Comment by paulehoffman** [comment]
It is indeed directly from RFC 1035; that is the "relevant standard".

We could add an example of an EDNS0 extension, but it would just appear as a bunch more hex.
