### ISSUE TITLE
Template expansion in POST

### ISSUE THREAD

**Issue by bemasc** [dohwg/draft-ietf-doh-dns-over-https#197]
The text says

> When using the POST method, the data payload MUST NOT be encoded and
> is used directly as the HTTP message body.

but it doesn't say where to send this message body.  Remember, we don't have a URL, only a URI template.  So I think we need some kind of text explaining how a POST client converts the template into a URL.  Presumably this is trivial (at least for the MTI format).

**Comment by mcmanus** [comment]
we do have a uri - its the output of processing a uri template

**Comment by mcmanus** [comment]
> The DNS API server defines the URI used by the request through the use of a URI Template.

> The URI Template defined in this document is processed without any variables when the HTTP method is POST. When the HTTP method is GET the single variable "dns" is defined as the content of the DNS request (as described in {{dnswire}}), encoded with base64url {{RFC4648}}.

**Comment by mcmanus** [comment]
ok to close?

**Comment by bemasc** [comment]
OK.
