### ISSUE TITLE
A single DNS packet query per HTTP request

### ISSUE THREAD

**Issue by bagder** [dohwg/draft-ietf-doh-dns-over-https#22]
It is not stated crystal clear in the -01 draft if there's only one DNS packet per HTTP request or if it is allowed to send more than one. Some wordings (like `the DNS query`) suggest a single packet. I think it would benefit the document to be more explicit on this detail.

**Comment by mcmanus** [comment]
good point - it is meant to be one, otherwise blocking and reordering (which is resolved at the intra-request http level) would be a problem. we'll add text.
