### ISSUE TITLE
OCSP stapling is required to prevent circular dependency for CRL/OCSP validation 

### ISSUE THREAD

**Issue by kmcskk** [dohwg/draft-ietf-doh-dns-over-https#26]
In order to prevent a dependency on traditional DNS or a DNS query for CRL/OCSP certificate validation check, OCSP stapling should be used for the HTTPS web server.

**Comment by mcmanus** [comment]
we're probably better off describing the potential deadlock in revocation and mentioning stapling as a best practice.. but in general I think we want to stay away from specifying a whole lot of how-to-profile-https details as these things do differ between clients and we tend to accept all of the variants as "https".. for e.g.
