### ISSUE TITLE
Spontaneous pushes of DNS queries and poisoning

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#27]
This protocol is a little bit special in the sense that clients that are DNS API capable will encounter servers that are able to push DNS requests and responses in the process of doing other things.

If a pushed response arrives, we need to make it clear that it would be poisoning to accept that response (and cache it).

To provide a concrete example, if a client has dns.example.net configured and it browses to www.example.com, then if www.example..com used server push to push a response that was otherwise a legitimate DNS API query, then that would NOT be treated as a DNS query, it would NOT enter the DNS cache.  Though it might enter the HTTP cache, the DNS API client would never ask for that response.

**Comment by mcmanus** [comment]
I'm going to mark this closed by c437e8ea

"the browser does not consult the DOH
server or use its responses for any DNS lookups outside the scope of
the application using them; i.e., there is (currently) no API that
allows a Web site to poison DNS for others."

let me know if you think it needs more juice
