### ISSUE TITLE
include base64url example

### ISSUE THREAD

**Issue by mcmanus** [dohwg/draft-ietf-doh-dns-over-https#30]
I've seen an implementation report that confused base64 and base64url; they noted that the examples didn't include one where the distinction was important

**Comment by chantra** [comment]
@mcmanus yes, there is also the bit about not having the `=` sign paddings that caught me at first. During the DOH proxy implementation, I missed the padding part. I have it implemented in

https://github.com/chantra/doh-proxy/blob/master/dohproxy/utils.py

```python
import base64

def doh_b64_encode(s):
    """Base 64 urlsafe encode and remove padding.
    input: bytes
    output: str
    """
    return base64.urlsafe_b64encode(s).decode('utf-8').rstrip('=')

def doh_b64_decode(s):
    """Base 64 urlsafe decode, add padding as needed.
    input: str
    output: bytes
    """
    padding = '=' * (-len(s)%4)
    return base64.urlsafe_b64decode(s + padding)
```

and I think it is correct :) Would an example implementation in a language be worth adding to the examples? It may be more straightforward to read than examples.

https://docs.python.org/3/library/base64.html#base64.urlsafe_b64encode documentation says:

```
which substitutes - instead of + and _ instead of / in the standard Base64 alphabet
```

This may be worth highlighting as what base64url is too.

**Comment by paulehoffman** [comment]
This is complicated by the fact that some people want the encoding of responses to GET to be media-type-specific.

**Comment by mcmanus** [comment]
> This is complicated by the fact that some people want the encoding of responses to GET to be media-type-specific.

I think you mean GET request body parameters (not responses - which are always in bodies and not encoded)

**Comment by paulehoffman** [comment]
Yes, I meant body parameters.

**Comment by martinthomson** [comment]
Please stop calling the parameter `body`.  It's really confusing.  (I just read this and thought to myself "GET doesn't have a body").

**Comment by mcmanus** [comment]
note that the current encoded url in the github copy is wrong as it wasn't updated when the dns id changed to 0. I'll fix that as part of making a base 64 example.
