### ISSUE TITLE
Discuss server flags?

### ISSUE THREAD

**Issue by hardaker** [dohwg/draft-ietf-doh-dns-over-https#46]
What do we think about discussing server (and possibly) client flags explicitly?  EG, is aDOH server allowed to be authoratative?  Can a client set the CD bit and expect it's internal API to honor that and not serve from http caching?  ...

**Comment by paulehoffman** [comment]
Please give more specific suggestions, hopefully one per issue. (To me, a DOH server can do whatever an recursive server can do, so I don't understand why there are even questions...)

**Comment by mcmanus** [comment]
I'm going to call this timed out from an issue tracker perspective. Feel free to re-raise if we can make some progress..
