### ISSUE TITLE
Please also consider Google DOH protocol as reference (w/ implementation)

### ISSUE THREAD

**Issue by m13253** [dohwg/draft-ietf-doh-dns-over-https#53]
The DOH draft proposed two formats, which are `application/dns-udpwireformat` and
`application/simpledns+json`. I would like to talk about the latter, which is not
defined yet, but already noted with the following references:

 -  https://tools.ietf.org/html/draft-dulaunoy-dnsop-passive-dns-cof
 -  https://tools.ietf.org/html/draft-bortzmeyer-dns-json

I want to suggest that, Google is offering DNS-over-HTTPS in another JSON
format. please consider this format in the standardization process of DOH JSON
format. The the API specification is at:

 -  https://developers.google.com/speed/public-dns/docs/dns-over-https

The difference of this format from bortzmeyer's is that, it has a uniform
presentation for various different RR types by not splitting up the data field,
thus easier to implement than some of other formats (as easy as taking the 5th
text field from the BIND zonefile).

As far as I knew, there are already some implementations supporting this
protocol, two note worthy clients are CoreDNS [1] and Dingo [2]. Dingo also
supports the OpenResolve protocol (similar to bortzmeyer's protocol).

I have implemented a DOH server / client suite [3] using the Google DOH
protocol. I extended the protocol with absolute TTL times to provide HTTP cache
semantics. This implementation has been put into stable public service for a
reasonable time. I would like to cooperate with the standardization with DOH
protocol, by implementing and experimenting with these formats, and hear
suggestions from you about the future development of DOH protocols.

 [1] https://coredns.io/plugins/proxy/
 [2] https://github.com/pforemski/dingo
 [3] https://github.com/m13253/dns-over-https

**Comment by paulehoffman** [comment]
Just to be clear: the current draft does **not** propose a JSON-based format. It has a fictitious format as an example.

The main reason for not supporting Google's protocol, or any of those listed, is that they restrict what DNS queries and responses can be passed. That is, they are each a (not well-defined) subset of the DNS semantic protocol. The community may want such a subset in the future, but I would hope that when the subset is chosen, it defines what is not allowed from the DNS semantic protocol and the community can decide whether that is a good idea, or maybe extend the format to cover more of the DNS.

**Comment by roryhewitt** [comment]
I came up with my own JSON-based format, but aside from playing on my own server, I haven't really implemented it yet (I started before I knew about Google's format, although I'd seen bortzmeyer's one).

[DoH JSON Format (v2).docx](https://github.com/dohwg/draft-ietf-doh-dns-over-https/files/1679560/DoH.JSON.Format.v2.docx)

@paulehoffman I'd make the case that there are some things that should/could never be implemented very well in a non-binary format (at least not a nice generic one) - zone transfers, for instance. But pretty much every 'get' can be done with a generic format, no?

**Comment by hardaker** [comment]
My points:

1. It's silly to require binary encoding if we're targeting languages and users that likely want to use text based encodings (like javascript)
2. My other thought (not really articulated before) is that it's likely too early to pick the default encoding format now anyway.  We likely need more experience before  defining a MUST implement "encoding X".

**Comment by paulehoffman** [comment]
@hardaker: a client that has all the features of RFC 1035 and successors (particularly EDNS0) is going to be mega-complicated already. The difference between "parse this 1035 format" and "understand every one of these tag-value pairs" is going to pale in comparison.

Also, it is not too early to pick a default encoding if there is only one that meets our requirements, which wireformat does. If someone does a complete JSON description, and we agree to weaken the second protocol requirement, then we should continue this discussion. So far, there has been no traffic on the list indicating that weakening the requirements is desired.

**Comment by m13253** [comment]
> a client that has all the features of RFC 1035 and successors (particularly EDNS0) is going to be mega-complicated already. The difference between "parse this 1035 format" and "understand every one of these tag-value pairs" is going to pale in comparison.

You are talking about the difficulty to implement a **DOH-to-DNS proxy**, instead of a **pure-DOH client**. If we reduce the difficulty of DOH-to-DNS proxy, we are increasing the complication of pure-DOH client.

The most beneficial application of DOH might be web-based applications, where only JavaScript can be used. In other situations DOH does not behave better than traditional UDP based DNS or DNSCrypt. Thus, why are we forcing a JavaScript-based client to parse DNS wire format?

Even if we are doing a DOH-to-DNS proxy, which is in fact not that complicated, at least easier than you might think: Most DNS library can do a conversion from DNS wire format to BIND Zone string format (and vice-versa) in one simple line of code, no matter what type of Qtype the query is in. Just take an example from [my implementation of Google JSON DNS](https://github.com/m13253/dns-over-https/blob/master/json-dns/marshal.go):

```go
 1	func marshalRR(rr dns.RR, now time.Time) RR {
 2		jsonRR := RR {}
 3		rrHeader := rr.Header()
 4		jsonRR.Name = rrHeader.Name
 5		jsonRR.Type = rrHeader.Rrtype
 6		jsonRR.TTL = rrHeader.Ttl
 7		jsonRR.Expires = now.Add(time.Duration(jsonRR.TTL) * time.Second)
 8		jsonRR.ExpiresStr = jsonRR.Expires.Format(time.RFC1123)
 9		data := strings.SplitN(rr.String(), "\t", 5)
10		if len(data) >= 5 {
11			jsonRR.Data = data[4]
12		}
13		return jsonRR
14	}
```

It's nothing more than these 14 lines, supporting all RR types including A, AAAA, MX, TXT, SRV, RRSIG, etc.

And also, JSON can do absolute TTL time, while UDP-wireformat cannot avoid the reparse-and-reconstruct process in order to correct the relative TTL. In other words, UDP-wireformat code still need to understand all RRs in order to get TTLs right.

---

> If someone does a complete JSON description, and we agree to weaken the second protocol requirement, then we should continue this discussion.

First, I agree that client does not need to speak both protocol. But I strongly recommends all servers should be able to speak both protocol. Otherwise, the client might need to negotiate a suitable protocol using `Content-Type` and `Accept`, wasting RTTs.

And I am willing to provide a complete description of a certain JSON format, with certain running code that at least we can immediately test on. Currently the format can encode all types of responses with Qclass=IN (Is there any networks alive except for the Internet?). The query supports DNSSEC and EDNS0-Client-Subnet extensions and I am willing to extend it.

---

> So far, there has been no traffic on the list indicating that weakening the requirements is desired.

Actually very large quantities of Internet companies have their propriety DNS over JSON protocol. Google has one, OpenDNS has one.

From my point of view in my homeland (China), connections between ISPs are slower than connections across distances, requiring high demand of EDNS0-Client-Subnet extension for CDNs to know the exact ISP of user, which is an extension not well adopted by local ISP's DNS servers, forcing large CDN provider to use JSON-based DNS systems. As far as I know, **all CDN providers** in China (except Akamai) uses ECS-enabled DNS systems, and over a half of them has **JSON-based DNS query API** incompatible with each other.

So why there are no traffic here? Probably because those companies have already established their own existing propriety protocols. Most of them do not want to pay for the effort to switch to the IETF standard. They probably do not even want to spend time arguing about which format is better.

---

By the way, I am currently implementing the IETF-draft-udp-wireformat protocol as a dual-stack option in my DNS-over-JSON software bundle mentioned above. It will be supporting TTL translation and EDNS0-Client-Subnet.

I will let you know when I finished, then we would be able to test on it.

**Comment by mcmanus** [comment]
I'm going to say this is out of scope for "draft-ietf-doh-dns-over-https" and therefore this specific github issues repository.

However I'm not claiming (not that I have the authority to claim, but I don't believe its true anyhow) that this is out of scope for the DoH Working Group (i.e. potentially a different document), So I think you should take this issue to the group mailing list (and perhaps we'll learn I'm wrong about my interpretation for the document as well.).

**Comment by m13253** [comment]
> So I think you should take this issue to the group mailing list

I tried to contact the working group mailling list way before I posted this issue but my mail was dropped. Is the mailling list open for any subscriber to post?

Now I knew that my proposal is too early and out of scope of this document. I think the best way is to wait for the primary `udpwire` format to complete.

Anyway, I do not think it is appropriate to close the issue before it is solved. Maybe it is better to give us an appropriate response about "whether / when are we going to be able to submit proposals about JSON format" instead of just repeating "JSON cannot cover all DNS packet types" here and #48 .

**Comment by bemasc** [comment]
The mailing list is open for any subscriber to post.  Make sure you are subscribed and confirmed before you try to post.

This issue tracker is just for this specific document, so anything that is out of scope of this document is also out of scope of this issue tracker.

Please join the mailing list and comment there.  You may also want to look at https://tools.ietf.org/html/draft-hoffman-dns-in-json-13, written by one of the authors.  That draft is currently targeted at the "Network" working group, not DOH.
