### ISSUE TITLE
Examples in 5.2 violate SHOULD in section 5

### ISSUE THREAD

**Issue by smutt** [dohwg/draft-ietf-doh-dns-over-https#54]
Section 5 states:

" In order to maximize cache friendliness, DNS API clients using media
   formats that include DNS ID, such as application/dns-udpwireformat,
   SHOULD use a DNS ID of 0 in every DNS request."

Yet the two examples given in section 5.2 have IDs of 0xabcd. I get that it's just a SHOULD, but wouldn't it be better if the examples followed it?

**Comment by paulehoffman** [comment]
s/better/obviously better/ :-)

**Comment by smutt** [comment]
Thanks Paul. Looks good. I think you can close.

**Comment by mcmanus** [comment]
closed by #58
