### ISSUE TITLE
May need a different ID for helping caching

### ISSUE THREAD

**Issue by paulehoffman** [dohwg/draft-ietf-doh-dns-over-https#68]
<https://tools.ietf.org/html/draft-ietf-dnsop-session-signal> is now in WG Last Call in the DNSOP WG. That draft makes the ID of 0 special for certain DNS requests (not all requests), but if the draft is approved, those requests might also want to be passed in DOH. We should pick a suggested ID that is not 0. If we pick one like 0xFFFF, we get the extra benefit of not needing a different example to differentiate base64url and base64 encoding.

**Comment by bemasc** [comment]
Is the session signalling draft compatible with DOH?  What if the HTTP requests are made using a non-DNS-aware client that spreads queries across a socket pool?

It seems to me that we could solve this by treating the ID number as a generic query-response framing layer for unframed transports, separate from the DNS messages, and remove it entirely in DOH.

**Comment by mcmanus** [comment]
I've only brielfy read session-signal, but it appears to require a stateful
transport for different DNS queries[1]. HTTP does not offer a stateful
application semantic[2] (e.g. connection management is not under the
control of the application - the application in this case being DOH). So
there probably isn't a conflict with using 0. (?)

[1] "DSO messages are used to communicate operations within persistent
stateful sessions"

[2] rfc7230 section 1.. this is part of the so called http semantic layer
(to be formalized by a current httpbis effort) and isn't changed by 7540

**Comment by paulehoffman** [comment]
session-signaling is compatible with DOH in the sense that it uses the same wire format as DNS. Unfortunately, its "I'm starting a session" request uses ID 0. 

I believe that HTTP will be considered stateful enough for session-signal, even if that makes HTTP people cringe. I think taking this into consideration for DOH is reasonable.

**Comment by mcmanus** [comment]
you're going to need to do more than assert HTTP is stateful enough. Its
not stateful at all :) (at least the HTTP semantic layer.. i.e. the version
independent layer that DOH utilizes... the stateful parts of rfc7540 (such
as hpack) are not exposed to the semantic layer)

session-signal itself points out in 4.1 that UDP is not suitable for
session-signal because it does not have in order message delivery. Neither
does DOH :)

-P

**Comment by paulehoffman** [comment]
If we're very sure of that, should I submit a WG Last Call comment on session-signal explicitly taking DNS-over-HTTPS out of their possible list of transports?

**Comment by mcmanus** [comment]
I didn't see that.. where is it listed? (they list dns-over-tls, but that's
not the same thing)

**Comment by paulehoffman** [comment]
A WG LC comment I want to make is that they should have a definitive list of transports (that can be expanded in the future). I can say that DOH must not be on that list. Don't forget that many DNS people still think that dns-over-tls and DOH are pretty much the same.

**Comment by mcmanus** [comment]
I think we ought to close this as a doh issue.

**Comment by paulehoffman** [comment]
Agree.
