### ISSUE TITLE
New query parameter names

### ISSUE THREAD

**Issue by roryhewitt** [dohwg/draft-ietf-doh-dns-over-https#69]
@mcmanus referring back to pull #19, you wrote this:

"I could go either way on body. You're right that the actual mime type is a bit of a problem.. I'll try it with a `ct` name argument without a value having the default meaning. I think that's explicit enough, while I don't really like totally implicit things like the absence of `ct` (what if you mis-spell it?)"

I'm fine with having `body` now named `dns`, but I'm concerned by the use of a the `ct` query parameter without a value at all...

Whilst this is probably too unwieldy:

    /dns-query?ct=application/dns-udpwireformat&dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB

the use of `ct` alone just seems...wrong:

    /dns-query?ct&dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB

Yes, I know it's valid according to RFC 3986, but I'm wondering whether, since it's very unlikely that a JSON format would be passed using a GET, we could treat the absence of `ct` as implying `ct=application/dns-udpwireformat`?

Alternatively we could allow a couple of special values for the `ct` parameter:

- `ct=binary` - implies that the format is `application/dns-udpwireformat`
- `ct=json` - implies that the format is `application/simpledns+json`

**Comment by martinthomson** [comment]
There's a potential different approach here, use a specific parameter name for each type of query.  That is, `dns=...` has a value that is `application/dns-udpwireformat, and `json=...` has a value that `application/dns-query+json` and so on.  That way you can have multiple formats on the request (for backwards compatibility).  The only downside is that the backwardly compatible request will cause a hit on cache coherency, so the server might want to redirect to a canonical URL if it is concerned that the client won't consistently include both formats.  (That redirect can be followed by a push if you are concerned about round trips.)

**Comment by paulehoffman** [comment]
This feels cache-unfriendly to me. What is the problem with the default for ct?

**Comment by martinthomson** [comment]
It's a tiny hit to cache unfriendliness (you don't get coherency between clients that inconsistently construct requests, or you have to redirect-and-push), agreed.  But it gets you the agility you wanted.

**Comment by roryhewitt** [comment]
@martinthomson So to be clear, you'd allow requests like any of the following:

`/dns-query?dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB`
`/dns-query?json={dns-query{[...`
`/dns-query?dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB&json={dns-query{[...`

Personally I like this - clear and neat. Maybe I'd change the `dns` parameter to `udp` (so the two options are `udp=<binary-value>` and `json=<sjon-value>`, but that's just me.

It removes the necessity to specify the type separately and it's 'neat'. Plus extensible for future formats.

**Comment by martinthomson** [comment]
Yeah.  Pick whatever colour you like for the shed, I'm not planning to live in it.

**Comment by mcmanus** [comment]
I think the color of the shed is fine for this document, and if discovery would like to do some fancy templating to enable rainbows that's fine for that separate effort.
