### ISSUE TITLE
Parameter names are pretty long

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#7]
`content-type` could be much shorter.  Bytes in requests matter and these are going to be used in critical conditions (early in the connection where the number of requests you can make depend on how big they are).  These won't compress well enough with HPACK to get any real benefit.

A short name would be an improvement.  A default value for `content-type` would be even better.

**Comment by roryhewitt** [comment]
Could go the alt-svc approach (https://tools.ietf.org/html/draft-ietf-httpbis-alt-svc-14#section-3.1) and use two-letter combos, e.g. "ct" for `content-type`, but really there out to be a standard for **that** approach...

**Comment by mcmanus** [comment]
closed via #19
