### ISSUE TITLE
Proposition on HTTP semantics caching & TTL adjusting

### ISSUE THREAD

**Issue by m13253** [dohwg/draft-ietf-doh-dns-over-https#70]
The previous doh draft is unfriendly to HTTP cache in two ways:

1. The DNS cache information is not transparent to HTTP cache proxies (e.g. CDN)
2. The TTL values is not up-to-date if retrieved from an HTTP cache proxy

The recent -03 version introduced a `Cache-Control` header, solving the first problem, but the second problem is still unresolved.

The consequence of an out-of-date TTL value may cause TTL bloating, which means a downstream server generates larger TTL value than the upstream server, eventually keeping stale DNS records for longer time than expected.

I am proposing a solution to the second problem:

1. The server SHOULD send a `Cache-Control` with both `public / private` and `max-age` values.

   If `Cache-Control: public`, the result MAY be cached for all users, generated when the authority nameserver is not ECS-aware, or the response contains ECS-scope = 0;
   If `Cache-Control: private`, the result SHOULD NOT be cached for all users, generated when the authority nameserver is ECS-aware, or the response contains ECS-scope != 0.
   For `Cache-Control: max-age=X`, X MUST be less or equal than the smallest TTL of all response records.

2. The server MUST send an optional `Last-Modified` and `Date` header.

3. The client SHOULD adjust the relative TTL according to `Last-Modified` and `Date`.

   If the client is a caching nameserver, providing access for other downstream servers, it MUST adjust the TTL value.
   The rule is described as follows:
   - Do nothing if `LastModified >= Now`.
   - `TTL = floor( TTL - (Now - LastModified) )`,
     where `floor` means rounding towards negative direction.
   - If TTL becomes negative, the client MUST either set it to zero,
     or OPTIONALLY resend the request in limited retry count.
   - Be careful, since not all TTL fields represent time values. [[Section 6.1.3, RFC 6891]](https://tools.ietf.org/html/rfc6891#section-6.1.3)

4. The TTL adjustment protocol only applies when `ct=application/dns-udpwireformat`.

I would like to hear some reply on my proposition. And if it is suitable, I hope it can be adopted in the next draft version.

**Comment by mcmanus** [comment]
> The TTL values is not up-to-date if retrieved from an HTTP cache proxy

I disagree with this characterization on a practical level. See the discussion of the age header for calculating the TTL when retrieving from cache. (the second paragraph of 7.1)

**Comment by m13253** [comment]
> See the discussion of the age header for calculating the TTL when retrieving from cache. (the second paragraph of 7.1)

Sorry I didn't noticed that a few days ago.

Actually my proposition is already identical as Section 7.1.

However there are some details I wanted to add to:

- TTL should be floor-rounded (in case it is not an integer, e.g. happens when the server uses `Expires` header).
- TTL should not be negative. Either use 0, or retry the request in a limited times.
- TTL should never be larger than before (e.g. happens when the server uses `Expires`).

**Comment by mnot** [comment]
Re-stating the requirements of other specs (in this case, RFC7234) is not a good idea. It defines how to calculate HTTP freshness, it shouldn't be redefined here.

**Comment by mcmanus** [comment]
closed based on the general editorial position of not restating other specs where we can avoid it - for fear of getting it wrong.
