### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by mnot** [dohwg/draft-ietf-doh-dns-over-https#72]
... says:

"""
DNS queries sometimes experience problems with end to end connectivity at times and places where HTTPS flows freely.

HTTPS provides the most practical mechanism for reliable end to end communication. Its use of TLS provides integrity and confidentiality guarantees and its use of HTTP allows it to interoperate with proxies, firewalls, and authentication systems where required for transit.
"""

Do we need to be talking about the motivation here? The way it's written sounds like it's using HTTP for tunnelling, which is something we wanted to avoid (especially if future efforts take away the message that HTTPS is the best tunnel).

**Comment by mcmanus** [comment]
I think the introduction does a decent job of dealing with the "not just a tunnel" question.. and therefore these motivators can live there and we can have a very simple 1 line abstract. (cutting non normative text is in vogue).. so I'll put up a PR that reflects that.
