### ISSUE TITLE
URI Templates

### ISSUE THREAD

**Issue by mnot** [dohwg/draft-ietf-doh-dns-over-https#74]
Right now DOH specifies static query parameters for its URLs to convey the content type of the DNS query as well as the actual query itself.

If DOH used [URI Templates](https://tools.ietf.org/html/rfc6570) ([implementation listing](https://github.com/uri-templates/uritemplate-spec/wiki/Implementations)) to describe the URLs that clients accessed, deployments wouldn't be locked into using those particular query arguments; the information needed could be conveyed anywhere in the URL, including the path or even the hostname.

E.g., your DOH service's template could be:

> https://doh.example.net/?ct={content_type}&dns={dns}

while mine could be:

> https://doh.example.org/{ct}/{dns}

or many other things, like:

> https://doh-{content_type}.example.org/whatever/?{dns}

This means that the protocol artefact used to configure a DOH service would be a URI template, not a URI.

**Comment by chantra** [comment]
As much as I like the flexibility this would bring to the protocol, having a predefined "required" protocol to universally support makes it easy to implement client/servers without going through the hoops of protocol discovery.
Say having GET with application/dns-udpwireformat being implemented universally. Discovery can be used to check and leverage other type of support like POST, or different formas: json, whatever other format coming next.

**Comment by mcmanus** [comment]
you should post this to the list to get wider review if you think its actually solves a problem. To me it smells like trying to apply architecture for the sake of applying architecture. If you keep going and end up with 75 you just, imo, end up with enough complexity that people won't bother to implement. For pretty marginal practical value.

Stipulated that you can always apply another layer of indirection.

**Comment by roryhewitt** [comment]
If there is no required format, then it's up to the requestor to know, in advance, what URI Template format each DOH server will use. Isn't that limiting? For instance, it means that I couldn't write generic code which could retrieve a response from any one of a number of DOH servers...

**Comment by mnot** [comment]
@roryhewitt yes, you need to know the template beforehand -- just like you need to know the URI now. They're both strings.

@mcmanus well, it solves #73. It gives a basis for the benefits outlined in #75 but does not require it; i.e., a discovery doc could be layered on afterwards, or optional.

**Comment by bemasc** [comment]
Conversely, discovery as in #75 does not require this kind of templating.  Fixed query structures are equally discoverable.

I would prefer to keep this protocol draft separate from any drafts on templating or discovery.  If you'd like to propose a new draft, please do so on the list.

**Comment by mcmanus** [comment]
this tracker is about a particular document and the direction we've gotten from the chairs is that discovery is not going to be handled in this document. so closing.
