### ISSUE TITLE
DOH discovery document

### ISSUE THREAD

**Issue by mnot** [dohwg/draft-ietf-doh-dns-over-https#75]
If URI templates are adopted (see #74) and you have a way of *discovering* the templates -- i.e. a file format that carries the templates in it -- several interesting things become possible.

For example, if you advertised your DOH service as living at `https://doh.example.net/`, it might return a file like this:

~~~ json
  {
    "api": {
      "title": "DOH",
      "links": {
        "describedBy": "urn:ietf:doh:v1"
      }
    },
    "resources": {
      "urn:ietf:doh:v1:": {
        "hrefTemplate": "/?ct={ct}&dns={dns}",
        "hrefVars": {
          "ct": "urn:ietf:doh:v1:content_type",
          "dns": "urn:ietf:doh:v1:dns"
        },
        "hints": {
          "allow": ["GET", "POST"],
          "formats": {
            "application/dns-udpwireformat": {}
          },
          "acceptPost": ["application/dns-udpwireformat"]
        }
      }
    }
  }
~~~

(note that the details here are VERY handwavy; please don't get distracted just yet)

This tells the client that the service implements DOHv1, and exposes a single resource templated with the URI template `/?ct={ct}&dns={dns}`. The variables in the template are mapped to IETF URNs that uniquely identify their semantics. 

Furthermore, it tells clients that the service allows both GET and POST requests, and accepts POSTs in the UDP wire format, and produces responses in the udp wire format as well.

(Aside: the above example happens to be in the format defined by [JSON Home](https://mnot.github.io/I-D/json-home/), which has been discussed extensively and implemented pretty diversely (so I think it could go to RFC relatively quickly), but that isn't to say that DOH has to use JSON Home; defining its own format might be more realistic, given milestones, etc.)

This would give DOH the ability to evolve more gracefully; new capabilities could be added by defining new formats, link relation types, etc., and be discovered at runtime by clients when they consume the document.

Mixing and matching APIs and extensions is much easier in this model too; because you're not locked into a particular pattern of URLs, and you're doing runtime discovery, versioning and extension doesn't need to be a monolithic v1...vn progression.

That can also be used for coordinating role-based access control, by the way. E.g., if you have a DNS update extension, but only want to expose it to authenticated users, you'd only put it in the documents you send to authenticated users.

I talk a little more about these benefits in [this blog entry](https://www.mnot.net/blog/2013/06/23/linking_apis).

AFAICT the downside with this approach is that the discovery document means one more round trip, but I think that's manageable; it can be cached pretty aggressively, after all, and in the use cases the WG is considering, it would be fetched at browser (or app) startup time, so it's unlikely the latency would be user perceivable.

**Comment by martinthomson** [comment]
@roryhewitt, Something has gone wrong if you need to version JSON like that.  The media type is usually a better way of signaling fundamental format differences.

**Comment by mcmanus** [comment]
this tracker is about a particular document and the direction we've gotten from the chairs is that discovery is not going to be handled in this document. so closing.
