### ISSUE TITLE
guidance on get/post

### ISSUE THREAD

**Issue by mcmanus** [dohwg/draft-ietf-doh-dns-over-https#82]
as discussed on list..

    1) Make one mandatory-to-implement
    2) Make both mandatory-to-implement
    3) Talk about why there is no mandatory-to-implemen

**Comment by paulehoffman** [comment]
At the face-to-face meeting, I thought the sense of the room was servers MUST implement both GET and POST,  clients can implement either or both. This needs to be confirmed on the list.

**Comment by paulehoffman** [comment]
See PR #128

**Comment by vttale** [comment]
My personal take of consensus is that, having heard no opposition to the position of @paulehoffman's summary above, to go with that.
