### ISSUE TITLE
tools.ietf.org doesn't parse Section 9 references

### ISSUE THREAD

**Issue by MikeBishop** [dohwg/draft-ietf-doh-dns-over-https#90]
In section 9 of DOH, it makes the following references:

> Sections 10.6 (Compression) and 10.7 (Padding) of [RFC7540] provide some further advice on mitigations within an HTTP/2 context.

This isn't one of the formats that the tools process will convert into deep links.  Instead, the "10.6" becomes a link to section 10.6 of DOH (which doesn't exist), while 10.7 doesn't become a link at all.

**Comment by mcmanus** [comment]
thanks. ugh.

**Comment by martinthomson** [comment]
HTTP/2 provides further advice about the use of compression (see Section 10.6 of [RFC7540]) and padding (Section 10.7 of [RFC7540]).

That removes the "mitigations" word.

**Comment by paulehoffman** [comment]
Fixed in  PR #91

**Comment by mcmanus** [comment]
closed by #91
