### ISSUE TITLE
DNS64 and DOH

### ISSUE THREAD

**Issue by mcmanus** [dohwg/draft-ietf-doh-dns-over-https#94]
wrt mailing list thread DNS64 and DOH

andrew sullivan suggests modifying an existing paragraph in operational considerations to have one new sentence:

> Local policy considerations and similar factors mean different DNS
   servers may provide different results to the same query: for instance
   in split DNS configurations [RFC6950].  It logically follows that the
   server which is queried can influence the end result.  Therefore a
   client's choice of DNS server may affect the responses it gets to its
   queries.  In the case of DNS64 [RFC6147], the choice could affect
   whether IPv6/IPv4 translation will work at all.

in my opinion that's fine. We don't need to enumerate everything, but DNS64 was already called out as a non goal so we might as well note this implication of that.

**Comment by paulehoffman** [comment]
PR #98

**Comment by mcmanus** [comment]
closed by #98
